### ISSUE TITLE
Adding DeserializerFilter to dispatch filters causes Fatal error

### ISSUE THREAD

**Issue by alecho** [loadsys/CakePHP-Serializers#112]
Following the installation instructions, adding 'Serializers.DeserializerFilter' via `Configure::write('Dispatcher.filters'...` causes A fatal error with the message:
```
Fatal error: Maximum function nesting level of '100' reached, aborting! in /var/www/Vendor/cakephp/cakephp/lib/Cake/Utility/Hash.php on line 48
```

**Comment by jtyost2** [comment]
More information please:

* What part of adding it?
* What was it trying to serialize or deserialize?
* Any other Dispatch Filters turned on?

**Comment by alecho** [comment]
I was just following the installation instructions in order on the README. It shouldn't be trying to serialize or deserialize anything. The default filters are on.

**Comment by jtyost2** [comment]
Hmm, it seems to work locally with a fresh Cake 2.6.3 install, running from the PHP web server.

Installation done via composer.

Sample bootstrap file and Cake home page attached.
![screen shot 2015-05-05 at 7 26 19 pm](https://cloud.githubusercontent.com/assets/85320/7486628/c6605cd2-f35c-11e4-93b1-8a50a868b3ed.png)
![screen shot 2015-05-05 at 7 26 24 pm](https://cloud.githubusercontent.com/assets/85320/7486629/c6632930-f35c-11e4-9821-9667f6964ad4.png)

**Comment by alecho** [comment]
Thanks for looking into this. I'll see what it specifically takes to duplicate. I'm on Cake 2.5 latest for this project but I doubt that's the issue.

**Comment by jtyost2** [comment]
Shouldn't be I don't do anything too special with Cake, and I test with Travis down to Cake 2.3.

**Comment by jtyost2** [comment]
Closing as we resolved this issue.

**Comment by alecho** [comment]
Just to note; issues was fixed in master just after I had installed the plugin.
