### ISSUE TITLE
strange issue with deserialization

### ISSUE THREAD

**Issue by brianally** [loadsys/CakePHP-Serializers#125]
Using the latest version of the plugin, Cake 2.6.3, PHP 5.5.9

I'm not using any custom classes for deserialization but the data is being returned in a funky way.

Posted data:

```
Array
(
  [user] => Array (
    [name] => foo
    [email] => foo@bar.net
    [agency] => 4
  )
)
```

DeserializerFilter::beforeDispatch() merges the deserialized data into $request->data, which then returns this:

```
Array
(
  [user] => Array (
    [name] => foo
    [email] => foo@bar.net
    [agency] => 4
  )

  [User] => Array (
    [name] => foo
    [email] => foo@bar.net
    [agency] => 4
  )
)
```

Note that there's now both "user" and "User".

However, in the controller, $this->request->data for some reason now appears like:

```
Array (
  [user] => Array (
    [name] => foo
    [email] => foo@bar.net
    [agency] => 4
  )
)
```

Thus, in the model, after $this->create($data), the data now looks like this in beforeValidate():

```
Array (
  [User] => Array (
    [user] => Array (
      [name] => foo
      [email] => foo@bar.net
      [agency] => 4
    )
  )
)
```

I don't know if it's the source of the problem, but it seems to me that it would be better to replace the array in $request->data rather than merge. Although, why/how the data goes back to just the lowercase user remains a mystery.

I'm already handling switching "agency" to "agency_id" in beforeValidate().

Something else i noticed: You're iterating over the data by key (modelName) to handle more than one model's data but overwriting $deserializedData each time.

```
$deserializedData = array();
foreach ($data as $key => $dataForKey) {
    $deserializedData = $this->deserializePostData($key, $data);
}
```

Shouldn't that be $deserializedData[] = ... ?

Also, i'm wondering if it would make more sense to pass $dataForKey rather than $data. Since you're passing the modelName as well, the data array doesn't need to be keyed by modelName.

**Comment by brianally** [comment]
The problem was with RequestHandler changing the data again in startup(). I'd been using RequestHandler before loading this plugin, and so i'd set the viewClass in the $components array like so:

```
'RequestHandler' =>array(
    'viewClassMap' => array(
        'json' => 'Serializers.EmberDataSerializer'
    )
)
```

I've removed RequestHandler altogether now and set $viewClass directly in AppController. All seems to work fine now.

**Comment by justinyost** [comment]
I'm going to close this issue then.

The docs suggest setting the `$viewClass` directly in AppController or whatever Controller needs to do this as well.
