### ISSUE TITLE
Updated Documentation to more clearly focus on Ember and Ember Data

### ISSUE THREAD

**Issue by jtyost2** [loadsys/CakePHP-Serializers#63]
The plugin as it stands today is designed for developing CakePHP REST API's to be consumed by Ember Data, so maybe mention that a little bit more.

- [x] Update Composer.json
- [x] Provide Text for Github Admins to edit the Project Description with 
- [x] Update the Readme to reflect this more clearly

**Comment by jtyost2** [comment]
@beporter Can you update the Github description text to read:

"A solution to serialize CakePHP response to JSON and correspondingly deserialize JSON into CakePHP data arrays, designed primarily around building REST APIs with Ember and Ember Data."

**Comment by beporter** [comment]
Done.

**Comment by jtyost2** [comment]
@beporter Thanks.

**Comment by jtyost2** [comment]
Marking as Closed as all tasks completed.
