### ISSUE TITLE
Update composer package name?

### ISSUE THREAD

**Issue by beporter** [loadsys/CakePHP-Serializers#95]
`loadsys/cakephp-serializers` ? Might have an impact on consuming projects and needs further investigation.

**Comment by jtyost2** [comment]
In short we probably can't easily:

> Please make sure you have read the package naming conventions before submitting your package. The authoritative name of your package will be taken from the composer.json file inside the master branch or trunk of your repository, and it can not be changed after that. [Cite](https://packagist.org/packages/submit)

> First of all, you must pick a package name. This is a very important step since it can not change and it should be unique enough to avoid conflicts in the future. [Cite](https://packagist.org/about)

Probably the only way to do so is to abandon the current package from Packagist and then possibly create a new package, but I'm not sure that would work.

Basically I think we are stuck with the name, we need to be about naming in the future (Making a note to add to the Plugin Skeleton Readme)

**Comment by jtyost2** [comment]
Readme for the Skeleton updated.
